### ISSUE TITLE
update to istio 1.0

### ISSUE THREAD

**Issue by bzd2000** [jaguarrr/istio-rancher-demo#1]
Hi,

I tried to install istio 1.0 (instead of istio 0.8) based on this tutorial but I have the following issues:

1.  I don't have a istio-ingress in the load balance tab, only a istio-ingressgateway
2. the istio-ingressgateway remains in pending althought I applied to work-around.

I tried some stuff already, but I don't get it working

Could you update this tutorial to istio 1.0?
That would be great.

thx,
Filip.

**Comment by roma-d** [comment]
Hey,

I'll try to update this one to Istio 1.0 this week and push the changes here.

**Comment by bzd2000** [comment]
ok super thx!

**Comment by roma-d** [comment]
hey @bzd2000, I've updated just now the guide to reflect the changes in Istio v1.0.2. Give it a try and let me know if you have any problems.

**Comment by bzd2000** [comment]
OK, I'll check it

**Comment by bzd2000** [comment]
When I create the app from the catague I get another error (I'm using local cluster)

Helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, certmanager : exit status 1****

![screenshot from 2018-10-19 12-02-03](https://user-images.githubusercontent.com/9049460/47211832-da8c8f00-d396-11e8-888f-9664c7e68c58.png)

**Comment by roma-d** [comment]
The steps from this article will not work in a local cluster, unfortunately, it requires public IPs and LoadBalancer functionality, that is not available in a local cluster.
Try it with Google Cloud Platform free trial, it provides more than enough resources to test it. I actually wrote the article using a Google Cloud Platform free trial.

**Comment by bzd2000** [comment]
I know, but free trial is consumed.  Maybe linked to the fact istio is already to versoin 1.1.0 now, instead of 1.0.2.
I don't see how to force in rancher to version 1.0.2

**Comment by roma-d** [comment]
Latest release of istio is still 1.0.2 as of now (1.1.0 is a prerelease), and that is the one that Rancher will use.
Actually, when I rewrote the steps for Istio 1.0.2, everything what was written for 0.8.0 was working. I'm almost sure it's a problem of the local cluster.

**Comment by bzd2000** [comment]
I tried with google cloud cluster, and I have the same error.

It is pulling the 1.1.0
![screenshot from 2018-10-19 14-28-35](https://user-images.githubusercontent.com/9049460/47218219-51cc1e00-d3ab-11e8-9da5-ed3ad0bf1044.png)

**Comment by roma-d** [comment]
The documentation still points to 1.0.2 version. 
The one you're referring to is Helm Template version, that might not be the same as the Istio version.
In any case, if you look at the screenshots in the article, there's also the 1.1.0 version and it worked fine.
