### ISSUE TITLE
[ERROR] CatalogController istio-github

### ISSUE THREAD

**Issue by erickcp** [jaguarrr/istio-rancher-demo#2]
hi @roma-d  im working on your tutorial and im having an error i cant fix =/ 

 [ERROR] CatalogController istio-github [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template istio-github-sidecarInjectorWebhook: Template.management.cattle.io "istio-github-sidecarInjectorWebhook"

do you know what is about? how can i fix it ? 
im new on kubernetes-istio-rancher ... so im having issues at every moment, ill really appreciate your help! 
greetings!

**Comment by roma-d** [comment]
hey @ecarvalloEcontact - my apologies for the late reply. Do you still have issues with following the tutorial?
If you can provide the steps you're taking I might be able to help you ;)

**Comment by erickcp** [comment]
hey @roma-d   i decided to try the istio setup using helm, i'm still not 100% comfortable with the result, I'm trying to create a production ready installation with k8s, istio, and rancher look great but at the end i had a lot of problems, and i'm new on this , so most of the problems i'm having  ( like the one i mentioned before )  y prefer to look for another alternative instead of work that much on troubleshooting , ill really apreciate if you can give me and advice for a better production ready setup for kubernetes and istio. greeting and thanks!

**Comment by roma-d** [comment]
Hey, @ecarvalloEcontact you can create a kubernetes cluster with Istio by default directly from Google Cloud Platform with Google Kubernetes Engine, there's an option to add Istio directly from there:

![image](https://user-images.githubusercontent.com/374405/50207011-e59f7380-0375-11e9-821d-9a23fae6efe6.png)

Afterwards you can import the cluster into Rancher and use it within Rancher, so you have Rancher and Istio.
Another option to istall Istio is to use Helm, that's still a very good option.

**Comment by erickcp** [comment]
thanks very much. i tried that instalation isnt bad, im still working on... 
thanks for the tips!! greetings
